version: "3"
services:
  stub:
    build: 
      context: docker/stub
  db:
    build: 
      context: docker/db
    depends_on:
      - stub
    network_mode: "service:stub"
  wordpress:
    image: wordpress:5.2.2-php7.3-fpm
    depends_on: 
      - stub
      - db
    restart: always
    network_mode: "service:stub"
    volumes:
      - wpdata:/var/www/html
  nginx:
    depends_on:
      - wordpress
      - stub
    build:
      context: docker/nginx
    restart: always
    network_mode: "service:stub"
    volumes:
      - wpdata:/var/www/html
volumes:
  wpdata:
